os:
  - Visual Studio 2017

platform:
  - x64

branches:
  only:
    - master

configuration:
  - Debug

before_build:
  - cmake -H. -BBuild -A%PLATFORM%

build:
  project: Build\pisa.sln
  parallel: true   
  verbosity: normal

test_script:
  - cd Build
  - ctest -V -j 2 -C %CONFIGURATION%

