PISA_BIN="/home/michal/pisa/build/bin"
INTERSECT_BIN="/home/michal/intersect/target/release/intersect"
BINARY_FREQ_COLL="/home/amallia/cw09b/CW09B.inv"
FWD="/home/amallia/cw09b/CW09B.fwd"
ENCODING="simdbp" # v1
BASENAME="/data/michal/work/v1/cw09b/cw09b-${ENCODING}"
THREADS=4
QUERIES="/home/michal/05.clean.shuf.test"
#QUERIES="/home/michal/topics.web.51-200.jl"
K=1000
OUTPUT_DIR="/data/michal/intersect/cw09b-est-lm"
#OUTPUT_DIR="/data/michal/intersect/cw09b-est-top20"
FILTERED_QUERIES="${OUTPUT_DIR}/$(basename ${QUERIES}).filtered"
#THRESHOLDS="/home/michal/biscorer/data/thresholds/cw09b/thresholds.cw09b.top1000.bm25.web.51-200"
#THRESHOLDS="/home/michal/biscorer/data/thresholds/cw09b/thresholds.cw09b.top1000.bm25.05.efficiency_topics.no_dups.1k"
#THRESHOLDS="/home/michal/biscorer/data/thresholds/cw09b/thresholds.cw09b.0_01.top15.bm25.05.efficiency_topics.no_dups.1k"
THRESHOLDS="/home/michal/biscorer/data/thresholds/cw09b/thresholds.cw09b.0_01.top20.bm25.05.clean.shuf.test"
