PISA_BIN="/home/michal/pisa/build/bin"
INTERSECT_BIN="/home/michal/intersect/target/release/intersect"
BINARY_FREQ_COLL="/home/amallia/cw09b/CW09B.inv"
FWD="/home/amallia/cw09b/CW09B.fwd"
ENCODING="simdbp" # v1
BASENAME="/data/michal/work/v1/cw09b/cw09b-${ENCODING}"
THREADS=4
QUERIES="/home/michal/05.clean.shuf.val"
K=1000
OUTPUT_DIR="/data/michal/intersect/cw09b-est-val"
FILTERED_QUERIES="${OUTPUT_DIR}/$(basename ${QUERIES}).filtered"
THRESHOLDS="/home/michal/biscorer/data/thresholds/cw09b/thresholds.cw09b.0_01.top20.bm25.05.clean.shuf.val"
