PISA_BIN="/home/michal/pisa/build/bin"
INTERSECT_BIN="/home/michal/intersect/target/release/intersect"
BINARY_FREQ_COLL="/data/CW12B/CW12B.url.inv"
FWD="/data/CW12B/CW12B.url.fwd"
ENCODING="simdbp" # v1
BASENAME="/data/michal/work/v1/cw12b-url/cw09b-${ENCODING}"
THREADS=4
QUERIES="/home/michal/05.clean.shuf.test"
K=1000
OUTPUT_DIR="/data/michal/intersect/cw12b-url"
FILTERED_QUERIES="${OUTPUT_DIR}/$(basename ${QUERIES}).filtered"
PAIRS=${FILTERED_QUERIES}
PAIR_INDEX_BASENAME="${BASENAME}-pair-trec05"
THRESHOLDS="/home/michal/biscorer/data/thresholds/cw12b/thresholds.cw12b.0_01.top20.bm25.05.clean.shuf.test"
QUERY_LIMIT=5000
