name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [gcc14, clang19]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Bulid docker image
      shell: bash
      run: |
        docker build \
          -t pisa -f- . < "${{runner.workspace}}/pisa/test/docker/${{matrix.compiler}}/Dockerfile"

    - name: Test
      shell: bash
      run: docker run pisa ctest -VV -j 4
