name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        compiler: [gcc13, clang15]
        standard: [17]
        include:
          - compiler: gcc13 # Extra test for C++20
            standard: 20

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Bulid docker image
      shell: bash
      run: |
        docker build --build-arg CXX_STANDARD=${{matrix.standard}} \
          -t pisa -f- . < "${{runner.workspace}}/pisa/test/docker/${{matrix.compiler}}/Dockerfile"

    - name: Test
      shell: bash
      run: docker run pisa ctest -VV -j 4
