name: Test Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        name: [gcc9, gcc10, gcc11, gcc12, clang11]
        include:
          - name: gcc9
          - name: gcc10
          - name: gcc11
          - name: gcc12
          - name: clang11

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Bulid docker image
      shell: bash
      run: docker build -t pisa -f- . < "${{runner.workspace}}/pisa/test/docker/${{matrix.name}}/Dockerfile"

    - name: Test
      shell: bash
      run: docker run pisa ctest -VV -j 4
